# Generated by Django 4.2.26 on 2025-11-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_employee_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending')], default='pending', max_length=50),
        ),
    ]
